FROM ubuntu:24.04

WORKDIR /app

RUN apt update \
&& apt-get -y install wget unzip fontconfig \
&& wget https://github.com/godotengine/godot/releases/download/4.4-stable/Godot_v4.4-stable_linux.arm64.zip -O /tmp/godot.zip \
&& unzip /tmp/godot.zip \
&& mv Godot_v4.4-stable_linux.arm64 /usr/local/bin/godot \
&& rm /tmp/godot.zip 


CMD ["godot", "--headless"]